name: Static Analysis
on:
    workflow_call:
        inputs:
            github-token:
                description: "secrets.GITHUB_TOKEN"
                required: true
                type: "string"
jobs:
    analyze:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
                                    
            - name: Fetch Pmd Config
              run: |
                  curl -o .github/workflows/pmd-rules.xml https://raw.githubusercontent.com/Cloud-Coach-Solutions/Github-Actions/main/.github/workflows/pmd-rules.xml
                  
#            - name: Setup PMD
#              uses: legetz/setup-pmd@7.0.0-rc3
                  
#            - name: Apex Classes Scan
#              run: |
#                  pmd check -f textcolor -R .github/workflows/pmd-rules.xml -d ./force-app/main/default/classes/*.cls
                  
#            - name: Apex Triggers Scan
#              run: |
#                  pmd check -f textcolor -R .github/workflows/pmd-rules.xml -d ./force-app/main/default/triggers/*.trigger
    
            - name: Install SFDX CLI and Scanner
              run: |
                  npm install sfdx-cli -g
                  sfdx plugins:install @salesforce/sfdx-scanner
                  
            - name: Run SFDX Scanner - Report findings as comments
              uses: mitchspano/sfdx-scan-pull-request@v0.1.15
              with:
                  pmdconfig: .github/workflows/pmd-rules.xml
                  severity-threshold: 1
                  report-mode: comments
                  delete-resolved-comments: true
              env:
                  GITHUB_TOKEN: ${{ inputs.github-token }}

            
