name: Static Analysis
on:
    workflow_call:
        inputs:
            github-token:
                description: "secrets.GITHUB_TOKEN"
                required: true
                type: "string"
jobs:
    analyze:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Install SFDX CLI and Scanner
              run: |
                  npm install sfdx-cli -g
                  sfdx plugins:install @salesforce/sfdx-scanner

            - name: log
              run: |
                  ls
                  ls .github
                  ls .github/workflows
                  cat .github/workflows/pmd-rules.xml

            - name: Run SFDX Scanner - Report findings as comments
              uses: mitchspano/sfdx-scan-pull-request@v0.1.15
              with:
                  pmdconfig: .github/workflows/pmd-rules.xml
                  severity-threshold: 1
                  report-mode: comments
                  delete-resolved-comments: true
              env:
                  GITHUB_TOKEN: ${{ inputs.github-token }}
